config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  root "static_pages#home"

  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

  resources :users, only: :show
  resources :exams

  namespace :admin do
    root "users#index"
    resources :users, except: [:show, :new, :create]
    resources :imports, only: :create
    resources :exams
    resources :categories do
      resources :questions, except: :show
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, :exetime, presence: true, uniqueness: false
  validates :exetime, numericality: {only_integer: true,
    greater_than: 0}

  private
  def self.to_csv options = {}
    CSV.generate options do |csv|
      csv << column_names
      all.each do |category|
        csv << category.attributes.values_at(*column_names)
      end
    end
  end

  def self.import file
    spreadsheet = open_spreadsheet file
    header = spreadsheet.row 1
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      category = find_by_name(row["name"]) || new
      category.attributes = row.to_hash
      category.save!
    end
  end

  def self.open_spreadsheet file
    if Settings.csv.type == File.extname(file.original_filename)
      Roo::CSV.new file.path
    else
      raise I18n.t("unfile") + "#{file.original_filename}"
    end
  end
end

app/controllers/admin/categories_controller.rb
require "csv"
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, except: [:new, :index, :create]

  def new
    @category = Category.new
  end

  def index
    @search = Category.search params[:q]
    @categories = @search.result.page params[:page]
    @search.build_condition if @search.conditions.empty?
    respond_to do |format|
      format.html
      format.csv {send_data @categories.to_csv}
    end
  end
  
  def show
  end

  def edit
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to [:admin, @category], flash: {success: t("update_success")}
    else
      render :new
    end
  end
  
  def update
    if @category.update_attributes category_params
      redirect_to [:admin, @category], flash: {success: t("update_success")}
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = t "delete_category"
    redirect_to admin_categories_url
  end

  private
  def set_category
    @category = Category.find params[:id]
  end

  def category_params
    params.require(:category).permit :name, :exetime
  end
end

app/views/admin/categories/_category.html.erb
<aside>
  <section class="user_info">
    <h1>
      <%= link_to category.name, [:admin, category] %>
      <%= link_to "", admin_category_path(category), method: :delete, data: {confirm: 
        t("you_sure")}, class: "glyphicon glyphicon-trash" %>
    </h1>
    <p>
      <%= t "exetime" %>
      <%= category.exetime %>
    </p>
    <p>
      <%= t "created_time" %>
      <%= category.created_at %>
    </p>
  </section>
</aside>

app/views/admin/categories/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
</div>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :exetime %>
  <%= f.number_field :exetime, class: "form-control" %>

  <%= f.submit button, class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/_imports_category_form.html.erb
<%= form_tag admin_imports_path, method: :post, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag t("import"), class: "btn btn-sm btn-info" %>
<% end %>

app/views/admin/categories/_search_form.html.erb
<div class="user_info">
<%= search_form_for @search, url: admin_categories_path,
  method: :get do |f| %>
    <%= f.condition_fields do |c| %>
      <%= render "condition_fields", f: c %>
    <% end %>
    <%= f.submit t("search"), class: "btn btn-sm btn-info"%>
<% end %>
</div>

app/views/admin/categories/edit.html.erb
<% provide :title, t("edit") %>
<h1><%= t "edit" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render "form", button: t("edit")%>  
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t("all_categories") %>

<div class="col-md-3">
  <%= render "search_form" %>
  <h2>
    <%= t "download" %>
    <%= link_to t("csv"), admin_categories_path(format: :csv) %>
  </h2>
  <h2><%= t "import_category" %></h2>
  <%= render "imports_category_form" %>
</div>
<div class="col-md-8">
  <h1><%= t "all_categories" %></h1>
  <ul class="users">
    <%= render @categories %>
  </ul>
  <%= will_paginate %>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, t("new_category") %>

<h1><%= t "new_category" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", button: t("create") %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% provide :title, @category.name %>
<div class="col-md-6 col-md-offset-3">
  <aside class="row">
    <section class="user_info">
      <h1>
        <%= @category.name %>
        <%= link_to t("edit"), edit_admin_category_path,
          class: "btn btn-default btn-lg" %>
      </h1>
      <p>
        <%= t "exetime" %>
        <%= @category.exetime %>
      </p>
      <p>
        <%= t "created_time" %>
        <%= @category.created_at %>
      </p>
      <p>
        <%= t "updated_time" %>
        <%= @category.updated_at %>
      </p>
      </br>
    </section>
    <section class= "content-section text-center">
      <%= link_to t("add_question"), new_admin_category_question_path(@category),
        class: "btn btn-default btn-lg" %>
    </section>
  </aside>
</div>
<div class="col-md-10 col-md-offset-1">
  <h1><%= t "all_questions" %></h1>
  <ul class="list-group">
    <% @category.questions.each do |question| %>
      <li class="list-group-item">
        <h1>
          <%= link_to question.content, [:edit, :admin, @category, question] %>
          <%= link_to t("delete"), [:admin, @category, question], method: :delete, 
            data: {confirm: t("you_sure")}, class: "btn btn-danger" %>
        </h1>
        <ul>
          <% question.answers.each do |answer| %>
            <li class="list-group">
              <%= answer.content %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>