config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  root "static_pages#home"

  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

  resources :users, only: :show
  resources :exams

  namespace :admin do
    root "users#index"
    resources :users, except: [:show, :new, :create]
    resources :imports, only: :create
    resources :exams
    resources :categories do
      resources :questions, except: :show
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :exams, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}

  before_create :set_default_role

  enum role: Settings.user.roles.to_h.keys

  def slug_candidates
    [:name, [:name, :id]]
  end

  private
  def set_default_role
    self.role ||= Settings.user.roles.normal
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  load_and_authorize_resource only: [:destroy]

  def index
    @users = User.paginate page: params[:page]
  end

  def destroy
    @user.destroy
    flash[:notice] = t "delete_user"
    redirect_to admin_users_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: Settings.avatar_size}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = Settings.avatar + "{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/admin/users/_user.html.erb
<aside>
  <section class="user_info">
    <h1>
      <%= link_to edit_admin_user_path(user) do %>
        <%= gravatar_for user, size: Settings.user.avatar_size %>
        <%= user.name %>
      <% end %>
      <%= link_to "", admin_user_path(user), method: :delete, data: {confirm: 
        t("you_sure")}, class: "glyphicon glyphicon-trash" %>
    </h1>
  </section>
</aside>

app/views/admin/users/index.html.erb
<% provide :title, t("all_user") %>

<h1><%= t "all_user" %></h1>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>