config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  root "static_pages#home"

  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

  resources :users, only: :show
  resources :exams

  namespace :admin do
    root "users#index"
    resources :users, except: [:show, :new, :create]
    resources :imports, only: :create
    resources :exams
    resources :categories do
      resources :questions, except: :show
    end
  end
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  has_many :results, dependent: :destroy
  has_many :questions, through: :results

  accepts_nested_attributes_for :results, allow_destroy: true,
    reject_if: :all_blank

  before_save :make_random_questions
  before_update :update_correct_answers, :mark_the_exam
  after_update :send_mail_admin, only: :update
  after_update :send_mail_to_user, only: :update

  scope :order_by_created_at, ->{order created_at: :DESC}
  scope :not_done, ->{where done: false}
  scope :expired, ->{not_done.where("created_at <= ?",
    Time.now - 168.hours)}

  private
  def make_random_questions
    @questions = category.questions.random_questions
    @questions.each {|question| results.build question: question}
  end

  def mark_the_exam
    self.correct_number = results.select{|result| result.correct}.count
  end

  def update_correct_answers
    results.each do |result|
      result.correct = result.answer.is_correct unless result.answer_id.nil?
    end
  end

  def send_mail_admin
    EmailWorker.perform_async self.id, self.user_id
  end

  def send_mail_to_user
    CheckedEmailWorker.perform_async self.id
  end
end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < ApplicationController
  load_and_authorize_resource
  before_action :check_admin_user

  def update
    @exam = Exam.find params[:id]
    if @exam.update_attributes exam_params
      flash[:success] = t :success_flash
      redirect_to admin_exam_path @exam
    else
      flash[:danger] = t :failed_flash
      render :edit
    end
  end

  private
  def exam_params
    params.require(:exam).permit :checked, results_attributes: [:correct, :id]
  end

  def check_admin_user
    redirect_to root_url if current_user.normal?
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  load_and_authorize_resource

  def index
    @exams = current_user.exams.order_by_created_at.paginate page: params[:page],
                                                             per_page: Settings.exam_page_size
    @exam = Exam.new
    @categories = Category.all
  end

  def show
    @exam = Exam.find params[:id]
  end

  def create
    @exam.user = current_user
    @exam.save ? flash[:success] = t(:success) : flash.now[:danger] = t(:fail)
    redirect_to exams_path
  end

  def edit
    @exam = Exam.find params[:id]
    if @exam.done?
      flash[:success] = t :done_flash
      redirect_to @exam
    end
  end

  def update
    @exam = Exam.find params[:id]
    if @exam.update_attributes exam_params
      flash[:success] = t :update_success
      redirect_to @exam
    else
      flash.now[:danger] = t :update_fail
      redirect_to :back
    end
  end

  private
  def exam_params
    params.require(:exam).permit :category_id, :done,
      :finished, results_attributes: [:id, :answer_id]
  end
end

app/views/exams/_exam.html.erb
<span class="col-md-1"></span>

<li>
  <span class="col-md-6">
  <%= exam.category.name %>
  </span>
  <span class="col-md-2">
    <% if exam.done? %>
      <%= link_to t(:view), exam_path(exam) %>
    <% else %>
      <%= link_to t(:start), edit_exam_path(exam) %>
    <% end %>
  </span>
</li>
<br>

app/views/exams/_row.html.erb
<tr>
  <td>
    <% if object.correct? %>
      <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    <% else %>
      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
    <% end %>
  </td>
  <td>
    <%= object.question.content %>
  </td>
</tr>

app/views/exams/edit.html.erb
<h1><%= t :exam %></h1>
<br>

<div class="clock">
  <span id="hour">00</span>
  <span>:</span>
  <span id="minute">00</span>
  <span>:</span>
  <span id="second">00</span>
</div>
<div class="center notice_exam"><%= I18n.t "notice.notice_submit" %></div><br>

<%= form_for @exam do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.hidden_field :done, value: true %>
  <%= f.hidden_field :finished, value: Time.now %>

  <%= f.fields_for :results do |builder| %>
    <%= render "result_form", f: builder %>
  <% end %>

  <div class="row">
    <%= f.submit t("submit"), class: "btn btn-primary submit-exam" %>
  </div>
  <br><br><br><br><br><br>
<% end %>

app/views/exams/index.html.erb
<% provide :title, t(:all_exams) %>
<h1><%= t :all_exams %></h1>
<br><br>
<div class="row">
  <div class="col-md-3">
  </div>

  <div class="col-md-3">
    <%= form_for @exam do |f| %>
      <div class="border-c">
        <%= f.hidden_field :user_id, value: current_user.id %>

        <table class="table table-bordered">
          <% @categories.each do |category| %>
            <tr>
              <td><%= f.radio_button :category_id, category.id %></td>
              <td><%= category.name %></td>
            </tr>
          <% end %>
        </table>

        <%= f.submit t(:create_an_exam), class: "start-new btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="col-md-1"></div>
  <div class="col-md-6">
    <div class="exams">
      <%= render @exams %>
    </div>
    <%= will_paginate %>
  </div>
</div>
<br>

app/views/exams/show.html.erb
<h2><%= t :test_result %></h2>

<div class="col-md-8 element one">
  <%= render @exam.results %>
</div>

<div class="col-md-4 element two">
  <p><%= t :result %>: <%= @exam.correct_number %><%= t "total_max_correct_number" %></p>
  <p><%= t :test_date %>: <%= @exam.updated_at %></p>
  <table class="table table-bordered">
    <tr>
      <th><%= t :correct %></th>
      <th><%= t :question %></th>
    </tr>
    <% @exam.results.each do |result| %>
      <%= render "row", object: result %>
    <% end %>
  </table>
</div>