config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  root "static_pages#home"

  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

  resources :users, only: :show
  resources :exams

  namespace :admin do
    root "users#index"
    resources :users, except: [:show, :new, :create]
    resources :imports, only: :create
    resources :exams
    resources :categories do
      resources :questions, except: :show
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t("about"), about_path %></li>
      <li><%= link_to t("contact"), contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("help"), help_path %></li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="divider"><%= link_to t("all_user"), admin_users_path %></li>
            <li class="dropdown">
              <%= link_to t("all_categories"), "#", class: "dropdown-toggle",
                data: {toggle: "dropdown"} %>
              <ul class="dropdown-menu">
                <li><%= link_to t("all_categories"), admin_categories_path %></li>
                <li><%= link_to t("Create"), new_admin_category_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("settings"), edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t("sign_out"), destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to t(:exams), exams_path %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("settings"), edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t("sign_out"), destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% end %>
        <% else %>
          <li><%= link_to t("sign_in"), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>